@Seeagle.Server_HostAddress = http://localhost:5251

GET {{Seeagle.Server_HostAddress}}/api/sample-names
Accept: application/json

###

POST {{Seeagle.Server_HostAddress}}/api/sample-names
Content-Type: application/json

{
  "name": "Helios"
}

###
